title: thatberd's blog
tagline: my personal blog
description: my personal blog
url: "https://thatberd.github.io"
baseurl: ""
paginate: 5
permalink: pretty

plugins:
  - jekyll-paginate
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock

sass:
  sass_dir: _sass
  style: :compressed

nav:
  - title: posts
    url: /posts
  - title: about
    url: /about
  - title: contact
    url: /contact

