title: thatberd
tagline: Personal dev blog
description: Personal dev blog
url: "https://thatberd.github.io"
baseurl: ""
paginate: 5
permalink: pretty

plugins:
  - jekyll-paginate
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock

sass:
  sass_dir: _sass
  style: :compressed

nav:
  - title: Posts
    url: /posts
  - title: Contact
    url: /contact
